FROM quay.io/keycloak/keycloak:20.0.2
USER root

ARG KEYCLOACK_PATH=/opt/keycloak
ARG HTTPS_CERTIFICATE_FILE
ARG HTTPS_CERTIFICATE_KEY_FILE

WORKDIR $KEYCLOACK_PATH

COPY ${HTTPS_CERTIFICATE_FILE} tls/
COPY ${HTTPS_CERTIFICATE_KEY_FILE} tls/

COPY ayr-realm.json data/
#COPY quarkus.properties conf/

ENV KC_HOSTNAME=${KC_HOSTNAME}

ENV KC_HTTPS_CERTIFICATE_FILE="${KEYCLOACK_PATH}/tls/${HTTPS_CERTIFICATE_FILE}"
ENV KC_HTTPS_CERTIFICATE_KEY_FILE="${KEYCLOACK_PATH}/tls/${HTTPS_CERTIFICATE_KEY_FILE}"


ENV DB_VENDOR=POSTGRES
ENV DB_ADDR=postgres
ENV DB_DATABASE=${KEYCLOACK_DB_NAME}
ENV DB_USER=${KEYCLOACK_DB_USER}
ENV DB_SCHEMA=public
ENV DB_PASSWORD=${KEYCLOACK_DB_PASSWORD}
ENV KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
ENV KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
