FROM quay.io/keycloak/keycloak:20.0.2
USER root

ARG KEYCLOACK_PATH=/opt/keycloak
ARG HTTPS_CERTIFICATE_FILE
ARG HTTPS_CERTIFICATE_KEY_FILE
ARG REALM_FILE

WORKDIR $KEYCLOACK_PATH

COPY ${HTTPS_CERTIFICATE_FILE} tls/
COPY ${HTTPS_CERTIFICATE_KEY_FILE} tls/

COPY ayr-realm.json data/

ENV KC_HOSTNAME=${KC_HOSTNAME}

ENV KC_HTTPS_CERTIFICATE_FILE="${KEYCLOACK_PATH}/tls/${HTTPS_CERTIFICATE_FILE}"
ENV KC_HTTPS_CERTIFICATE_KEY_FILE="${KEYCLOACK_PATH}/tls/${HTTPS_CERTIFICATE_KEY_FILE}"

ENV KC_DB=postgres
ENV KC_DB_URL_HOST=${KC_DB_URL_HOST}
ENV KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
ENV KC_DB_USERNAME=${KC_DB_USERNAME}
ENV KC_DB_PASSWORD=${KC_DB_PASSWORD}

ENV KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
ENV KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
