name: Docker Build ECR Push
on:
  push:
    branches: ['dev']
  workflow_dispatch:
jobs:
  docker-build-push-ecr:
    uses: nationalarchives/da-ayr-github-actions/.github/workflows/docker-build-ecr-ecs-deploy-kc.yml@dev
    secrets:
      AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO }}
      AWS_ECR_AND_ECS_ROLE_ARN: ${{ secrets.AWS_ECR_AND_ECS_ROLE_ARN }}
      AWS_NONPROD_ACCOUNT: ${{ secrets.AWS_NONPROD_ACCOUNT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_REGISTRIES: ${{ secrets.AWS_REGISTRIES }}
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
